services:
- type: web
  name: client
  env: static
  buildCommand: ng build --prod
  staticPublishPath: dist/client
  routes:
     - type: redirect
       source: /*
       destination: /index.html
 
